title: Duck
author: Marcel
description: >-
  This page is about ducks.
baseurl: ""
url: "https://eend.org"
favicon: "./favicon.ico"

show_excerpts: false

# Build settings
theme: moving

moving:
  about_you: "Something about me"
  back_to: "Home"
